# Generated by Django 5.1.6 on 2025-02-28 09:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Banner Görseli')),
                ('button_text', models.CharField(max_length=50, verbose_name='Buton Metni')),
                ('button_url', models.CharField(max_length=100, verbose_name='Buton URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Görsel')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('author', models.CharField(max_length=100, verbose_name='Yazar')),
                ('publish_date', models.DateField(verbose_name='Yayın Tarihi')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu Mu?')),
            ],
            options={
                'verbose_name': 'İletişim Formu',
                'verbose_name_plural': 'İletişim Formları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Adres')),
                ('email1', models.EmailField(max_length=254, verbose_name='E-posta 1')),
                ('email2', models.EmailField(blank=True, max_length=254, verbose_name='E-posta 2')),
                ('phone1', models.CharField(max_length=20, verbose_name='Telefon 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Telefon 2')),
                ('map_url', models.URLField(verbose_name='Harita URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
            ],
            options={
                'verbose_name': 'İletişim Bilgisi',
                'verbose_name_plural': 'İletişim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Flaticon İkonu')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('animation_delay', models.CharField(default='.3s', max_length=10, verbose_name='Animasyon Gecikmesi')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
            ],
            options={
                'verbose_name': 'Uzmanlık',
                'verbose_name_plural': 'Uzmanlıklar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Görsel')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
            ],
            options={
                'verbose_name': 'Portföy',
                'verbose_name_plural': 'Portföy',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Örn: flaticon-law', max_length=50, verbose_name='Flaticon İkonu')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('button_text', models.CharField(default='Devamını Oku', max_length=50, verbose_name='Buton Metni')),
                ('button_url', models.CharField(max_length=100, verbose_name='Buton URL')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
            ],
            options={
                'verbose_name': 'Uzmanlık Alanı',
                'verbose_name_plural': 'Uzmanlık Alanları',
                'ordering': ['order'],
            },
        ),
    ]
