# Generated by Django 5.1.6 on 2025-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_lawyer_lawyercertificate_lawyerexpertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Yanıt'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yanıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu'),
        ),
    ]
