# Generated by Django 5.1.6 on 2025-02-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_contactform_response_contactform_response_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Şablon Başlığı')),
                ('content', models.TextField(verbose_name='Şablon İçeriği')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Yanıt Şablonu',
                'verbose_name_plural': 'Yanıt Şablonları',
                'ordering': ['order', 'title'],
            },
        ),
    ]
