# Generated by Django 5.1.6 on 2025-02-28 18:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_responsetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dava Başlığı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('case_type', models.CharField(choices=[('criminal', 'Ceza Hukuku'), ('civil', 'Medeni Hukuk'), ('commercial', 'Ticaret Hukuku'), ('labor', 'İş Hukuku'), ('family', 'Aile Hukuku'), ('cyber', 'Siber Hukuk'), ('education', 'Eğitim Hukuku'), ('inheritance', 'Miras Hukuku'), ('execution', 'İcra Hukuku'), ('administrative', 'İdare Hukuku'), ('tax', 'Vergi Hukuku'), ('other', 'Diğer')], max_length=20, verbose_name='Dava Türü')),
                ('status', models.CharField(choices=[('ongoing', 'Devam Ediyor'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi'), ('settled', 'Uzlaşma Sağlandı'), ('appealed', 'Temyizde')], max_length=20, verbose_name='Durum')),
                ('summary', models.TextField(verbose_name='Özet')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Detaylı Açıklama')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('client_type', models.CharField(help_text='Örn: Bireysel, Kurumsal', max_length=100, verbose_name='Müvekkil Türü')),
                ('result', models.TextField(blank=True, verbose_name='Sonuç')),
                ('featured_image', models.ImageField(blank=True, upload_to='cases/', verbose_name='Kapak Görseli')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan Dava')),
                ('is_public', models.BooleanField(default=True, verbose_name='Yayında')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Örnek Dava',
                'verbose_name_plural': 'Örnek Davalar',
                'ordering': ['-is_featured', 'order', '-start_date'],
            },
        ),
    ]
