# Generated by Django 5.1.6 on 2025-02-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0005_casestudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='case_type',
            field=models.CharField(choices=[('Ceza Hukuku', 'Ceza Hukuku'), ('Medeni Hukuk', 'Medeni Hukuk'), ('Ticaret Hukuku', 'Ticaret Hukuku'), ('İş Hukuku', 'İş Hukuku'), ('Aile Hukuku', 'Aile Hukuku'), ('Siber Hukuk', 'Siber Hukuk'), ('Eğitim Hukuku', 'Eğitim Hukuku'), ('Miras Hukuku', 'Miras Hukuku'), ('İcra Hukuku', 'İcra Hukuku'), ('İdare Hukuku', 'İdare Hukuku'), ('Vergi Hukuku', 'Vergi Hukuku'), ('Diğer', 'Diğer')], max_length=20, verbose_name='Dava Türü'),
        ),
    ]
