from django.urls import path
from . import views

app_name = 'webui'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('attorney/', views.attorney, name='attorney'),
    path('attorney-details/<int:id>/', views.attorney_details, name='attorney_details'),
    path('practice/', views.practice, name='practice'),
    path('practice-details/<int:id>/', views.practice_details, name='practice_details'),
    path('case-study/', views.case_study, name='case_study'),
    path('case-study-details/<int:id>/', views.case_study_details, name='case_study_details'),
    path('blog/', views.blog, name='blog'),
    path('blog-details/<int:id>/', views.blog_details, name='blog_details'),
    path('contact/', views.contact, name='contact'),
    path('appointment/', views.appointment, name='appointment'),
    path('privacy-policy/', views.privacy_policy, name='privacy'),
    path('terms-conditions/', views.terms_conditions, name='terms_conditions'),
    path('coming-soon/', views.coming_soon, name='coming_soon'),
    path('contact/submit/', views.contact_form_submit, name='contact_form_submit'),
    path('messages/', views.message_list, name='message_list'),
    path('messages/<int:form_id>/response/', views.message_response, name='message_response'),
    path('api/templates/<int:template_id>/', views.get_template, name='get_template'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('management/', views.management_dashboard, name='management_dashboard'),
    path('management/banners/', views.banner_list, name='banner_list'),
    path('management/banners/create/', views.banner_create, name='banner_create'),
    path('management/banners/<int:id>/edit/', views.banner_edit, name='banner_edit'),
    path('management/banners/<int:id>/delete/', views.banner_delete, name='banner_delete'),
    path('management/practices/', views.practice_list, name='practice_list'),
    path('management/practices/create/', views.practice_create, name='practice_create'),
    path('management/practices/<int:id>/edit/', views.practice_edit, name='practice_edit'),
    path('management/practices/<int:id>/delete/', views.practice_delete, name='practice_delete'),
    path('management/lawyers/', views.lawyer_list, name='lawyer_list'),
    path('management/lawyers/create/', views.lawyer_create, name='lawyer_create'),
    path('management/lawyers/<int:id>/edit/', views.lawyer_edit, name='lawyer_edit'),
    path('management/lawyers/<int:id>/delete/', views.lawyer_delete, name='lawyer_delete'),
    path('management/blog/', views.blog_list, name='blog_list'),
    path('management/blog/create/', views.blog_create, name='blog_create'),
    path('management/blog/<int:id>/edit/', views.blog_edit, name='blog_edit'),
    path('management/blog/<int:id>/delete/', views.blog_delete, name='blog_delete'),
    path('management/contact-info/', views.contact_info, name='contact_info'),
    path('management/contact-info/edit/', views.contact_info_edit, name='contact_info_edit'),
    path('management/cases/', views.case_list, name='case_list'),
    path('management/cases/create/', views.case_create, name='case_create'),
    path('management/cases/<int:id>/edit/', views.case_edit, name='case_edit'),
    path('management/cases/<int:id>/delete/', views.case_delete, name='case_delete'),
] 